config/routes.rb
FactoryGirlWeb::Engine.routes.draw do
  root "fixtures#index"
  post "/" => "fixtures#create", as: :fixtures
end

app/models/factory_girl_web/fixture.rb
module FactoryGirlWeb
  class Fixture
    include ActiveModel::Model

    attr_accessor :name, :traits, :amount

    delegate :factories, to: :class

    with_options presence: true do
      validates :name
      validates :amount, numericality: { only_integer: true, greater_than: 0 }
    end

    def create
      return unless valid?

      ActiveRecord::Base.transaction do
        FactoryGirl.create_list(name.to_sym, amount.to_i, *formatted_traits)
      end
    end

    def name_i18n
      name.to_s.classify.safe_constantize.try(:model_name).try(:human) || name
    end

    def defined_traits
      factories[name] || []
    end

    private

    def formatted_traits
      return [] if traits.blank?
      traits.map(&:to_sym)
    end

    class << self
      def all
        factories.keys.map { |name| new(name: name, amount: 1) }
      end

      def factories
        @factories ||= begin
          FactoryGirl.factories.sort_by(&:name).each_with_object(HashWithIndifferentAccess.new) do |factory, h|
            h[factory.name] = factory.defined_traits.map(&:name)
          end
        end
      end
    end
  end
end

app/controllers/factory_girl_web/application_controller.rb
module FactoryGirlWeb
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/factory_girl_web/fixtures_controller.rb
require_dependency "factory_girl_web/application_controller"

module FactoryGirlWeb
  class FixturesController < ApplicationController
    def index
      @fixtures = Fixture.all
    end

    def create
      fixture = Fixture.new(permitted_params)

      if fixture.create
        redirect_to :back, notice: format("%{model} was successfully created.", model: fixture.name_i18n)
      else
        redirect_to :back, alert: fixture.errors.full_messages.to_sentence
      end
    end

    private

    def permitted_params
      params.require(:fixture).permit(:name, :traits, :amount)
    end
  end
end

app/helpers/factory_girl_web/application_helper.rb
module FactoryGirlWeb
  module ApplicationHelper
  end
end

app/views/factory_girl_web/fixtures/index.html.slim
- @fixtures.each_slice(4) do |fixtures|
  .row
    - fixtures.each do |fixture|
      .col-md-3
        .card
          .card-block
            h6.card-title = fixture.name_i18n
            = form_for fixture, url: fixtures_path do |f|
              = f.hidden_field :name
              .form-group
                = f.label :traits
                = f.select :traits, fixture.defined_traits, {}, multiple: true, size: 3, include_blank: false, class: "form-control"
              .form-group
                = f.label :amount
                = f.number_field :amount, min: 1, required: true, class: "form-control"
              = f.button :create, class: "btn btn-outline-primary"

app/views/layouts/factory_girl_web/application.html.slim
doctype html
html
  head
    title factory girl web
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = stylesheet_link_tag "//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css"
    css:
      #main {
        margin-top: 4.5rem;
      }
      .card {
        font-size: 85%;
        overflow: hidden;
      }
      select.form-control {
        overflow: auto;
      }
      footer {
        padding: 1.5rem 0;
        font-size: 80%;
        color: #888;
      }
  body
    = render partial: "shared/factory_girl_web/header"

    .container-fluid#main
      - if notice
        .alert.alert-success role="alert"
          small = notice
      - if alert
        .alert.alert-warning role="alert"
          small = alert
      = yield

    = render partial: "shared/factory_girl_web/footer"

app/views/shared/factory_girl_web/_footer.html.slim
footer
  .container-fluid
    ul.nav.nav-inline
      li.nav-item Powered by #{link_to "factory girl web", "https://github.com/yhirano55/factory_girl_web", class: "nav-link"} #{FactoryGirlWeb::VERSION}

app/views/shared/factory_girl_web/_header.html.slim
header
  nav.navbar.navbar-fixed-top.navbar-dark.bg-inverse
    .nav.navbar-nav
      = link_to "factory girl web", root_path, class: "nav-item nav-link active"